version: "3.7"
services:
  localizacao-api:
    container_name: localizacao-api
    build:
      context: '.'
      args:
        uid: ${UID}
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}

  localizacao-db:
    container_name: localizacao-db
    image: mysql
    volumes:
      - mysql_storage:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: localizacao
      MYSQL_DATABASE: localizacao
      MYSQL_USER: localizacao
      MYSQL_PASSWORD: localizacao

  localizacao-redis:
    container_name: localizacao-redis
    image: redis:6-alpine
    command: redis-server --requirepass adressen

  composer:
    image: composer
    user: ${UID}
    command: composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts
    volumes:
      - ./:/app

volumes:
  mysql_storage: {}
